# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48a146d92a02ff3257fe272d44ee7a79c04ba700beadd0c5d2707fe1ccfe9df9694957ac8d51a8ccfabdb828262ea90688d55ba41846948a5376931a0a95ddc7

test:
  secret_key_base: b9bf64d563b16e8198d6ca5420e46d24acd3ac1714a9c81e2b71320cd72a08545fda289dc693b7b4d709948d3165a82181748aa3588388bf0b6b94d2ee40ac3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
